export const universities = [
  { id: 1, name: "Harvard University" },
  { id: 2, name: "Stanford University" },
  { id: 3, name: "Massachusetts Institute of Technology (MIT)" },
  { id: 4, name: "California Institute of Technology (Caltech)" },
  { id: 5, name: "Princeton University" },
  { id: 6, name: "Yale University" },
  { id: 7, name: "Columbia University" },
  { id: 8, name: "University of Chicago" },
  { id: 9, name: "University of California, Berkeley" },
  { id: 10, name: "University of Pennsylvania" },
  { id: 11, name: "Stanford University" },
  { id: 12, name: "University of Michigan" },
  { id: 13, name: "Duke University" },
  { id: 14, name: "Johns Hopkins University" },
  { id: 15, name: "Northwestern University" },
  { id: 16, name: "University of California, Los Angeles (UCLA)" },
  { id: 17, name: "University of Virginia" },
  { id: 18, name: "University of Florida" },
  { id: 19, name: "New York University (NYU)" },
  { id: 20, name: "University of Texas at Austin" },
  { id: 21, name: "University of New Hampshire" },
];
